### ISSUE TITLE
How to open the DEBUG mode please? (to view the error and solve 502 error)

### ISSUE THREAD

**Issue by Xingeqwd** [xNul/code-llama-for-vscode#9]
Hello, masters

i have a GGML API server(with the llamacpp_mock_api.py) and a continuedev-server, on a same linux server

when i use the continuedev-server send request to Ollama-api, the continuedev-server return `Error calling /chat/completions endpoint: 502`

I not sure what request was send to GGML, i thought this should be the reason to this problem

i want to see the GGML API log to find out these, 
but dont know where the log is, so i came to ask about that

I only have the continue-dev server stdout, says "DEBUG=off", i thought, if DEBUG opened, the log will be showned

```

(codellama) root@********# torchrun --nproc_per_node 1 llamacpp_mock_api.py     --ckpt_dir CodeLlama-7b-Instruct/     --tokenizer_path CodeLlama-7b-Instruct/tokenizer.model     --max_seq_len 1024 --max_batch_size 4
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
/root/anaconda3/envs/codellama/lib/python3.10/site-packages/torch/__init__.py:614: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:451.)
  _C._set_default_tensor_type(t)
Loaded in 7.50 seconds
 * Serving Flask app 'llamacpp_mock_api'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:8888
Press CTRL+C to quit


```

**the continue-server log are as below**
```
[2023-11-02 16:56:53] [ERROR] Error while running step: 
Traceback (most recent call last):

  File "/root/anaconda3/envs/continue-dev/lib/python3.10/site-packages/continuedev/core/autopilot.py", line 218, in _run_singular_step
    async for update in step.run(self.sdk):

  File "/root/anaconda3/envs/continue-dev/lib/python3.10/site-packages/continuedev/plugins/steps/chat.py", line 50, in run
    async for chunk in generator:

  File "/root/anaconda3/envs/continue-dev/lib/python3.10/site-packages/continuedev/libs/llm/base.py", line 475, in stream_chat
    async for chunk in self._stream_complete(prompt=prompt, options=options):

  File "/root/anaconda3/envs/continue-dev/lib/python3.10/site-packages/continuedev/libs/llm/ggml.py", line 271, in _stream_complete
    async for chunk in self._raw_stream_complete(prompt, options):

  File "/root/anaconda3/envs/continue-dev/lib/python3.10/site-packages/continuedev/libs/llm/ggml.py", line 134, in _raw_stream_complete
    raise Exception(

Exception: Error calling /chat/completions endpoint: 502

Error calling /chat/completions endpoint: 502

```

 
I thought there should be somewhere to open the DEBUG-MODE
because the DEBUG-MODE is off, should be this causing the log dont display

I have see the Google, this github repository, and something else, but dont found something valuable

________________

Thanks to everyone, hope you all have a good and nice day and life!

BTW, my issue when deploying the continue server is [issues#570](https://github.com/continuedev/continue/issues/570)
the newest reply was send by me, this contained the logs etc. i haven't add these here

**Comment by Xingeqwd** [comment]
no problem, masters, 
this was sloved, 
thanks, and wish everyone have a nice life!
